---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clair-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  nfs:
    server: 10.0.0.134
    path: /data/app1/clair
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clair-pvc
  namespace: clair
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clair-postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  nfs:
    server: 10.0.0.134
    path: /data/app1/clair-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clair-postgres-pvc
  namespace: clair
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clair-config
  namespace: clair
data:
  config.yaml: |
    # Clair configuration file
    http_listen_addr: :8080
    introspect_addr: :8089
    log_level: info
    
    database:
      type: pgsql
      options:
        source: postgresql://clair:password@clair-postgres:5432/clair?sslmode=disable
        cachesize: 16384
    
    updater:
      interval: 6h
    
    notifier:
      attempts: 3
      renotifyinterval: 1h
      http:
        endpoint: http://clair:8080/notifier/api/v1/notifications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clair-postgres
  namespace: clair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clair-postgres
  template:
    metadata:
      labels:
        app: clair-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: "clair"
        - name: POSTGRES_USER
          value: "clair"
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: clair-postgres-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clair
  namespace: clair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clair
  template:
    metadata:
      labels:
        app: clair
    spec:
      containers:
      - name: clair
        image: quay.io/projectquay/clair:4.7
        ports:
        - containerPort: 8080
        - containerPort: 8089
        volumeMounts:
        - name: config-volume
          mountPath: /etc/clair
        - name: clair-data
          mountPath: /var/lib/clair
        env:
        - name: CLAIR_CONF
          value: /etc/clair/config.yaml
        - name: CLAIR_MODE
          value: "combo"
      volumes:
      - name: config-volume
        configMap:
          name: clair-config
      - name: clair-data
        persistentVolumeClaim:
          claimName: clair-pvc
      initContainers:
      - name: wait-for-postgres
        image: postgres:13
        command: ['sh', '-c', 'until pg_isready -h clair-postgres -p 5432; do echo waiting for database; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: clair-postgres
  namespace: clair
spec:
  selector:
    app: clair-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: clair
  namespace: clair
spec:
  type: NodePort
  selector:
    app: clair
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: introspect
    port: 8089
    targetPort: 8089
    nodePort: 30089
---
apiVersion: v1
kind: Namespace
metadata:
  name: clair
